eureka.server.ip.peer1: 172.16.0.26
eureka.server.ip.peer2: 172.16.0.27
eureka.server.ip.peer3: 172.16.0.43

peer1.port: 8762
peer2.port: 8763
peer3.port: 8764

eureka.server.ip.kafka: 172.16.0.27

eureka.registry.server.user: horcrux
eureka.registry.server.passwd: hor66

eureka.registry.peer1.url: http://horcrux:hor66@${eureka.server.ip.peer1}:${peer1.port}/eureka
eureka.registry.peer2.url: http://horcrux:hor66@${eureka.server.ip.peer2}:${peer2.port}/eureka
eureka.registry.peer3.url: http://horcrux:hor66@${eureka.server.ip.peer3}:${peer3.port}/eureka